[package]
name = "kona-node"
version = "0.1.0"
description = "Kona Consensus Node"

edition.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true
repository.workspace = true
categories.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
# workspace
kona-cli.workspace = true
kona-peers.workspace = true
kona-derive.workspace = true
kona-sources.workspace = true
kona-genesis.workspace = true
kona-protocol.workspace = true

kona-p2p.workspace = true
kona-rpc.workspace = true
kona-disc = { workspace = true, features = ["metrics"] }
kona-gossip = { workspace = true, features = ["metrics"] }
kona-engine = { workspace = true, features = ["metrics"] }
kona-registry = { workspace = true, features = ["tabled"] }
kona-node-service = { workspace = true, features = ["metrics"] }

# alloy
alloy-provider.workspace = true
alloy-transport.workspace = true
alloy-primitives.workspace = true
alloy-rpc-types-engine = { workspace = true, features = ["jwt", "serde"] }

# op-alloy
op-alloy-provider.workspace = true

# general
futures.workspace = true
rstest.workspace = true
url.workspace = true
dirs.workspace = true
backon.workspace = true
tokio-stream.workspace = true
discv5.workspace = true
tabled.workspace = true
libp2p.workspace = true
anyhow.workspace = true
metrics.workspace = true
tracing.workspace = true
serde_json = { workspace = true, features = ["std"] }
jsonrpsee = { workspace = true, features = ["server"] }
clap = { workspace = true, features = ["derive", "env"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tracing-subscriber = { workspace = true, features = ["fmt", "env-filter"] }

[dev-dependencies]
rstest.workspace = true

[build-dependencies]
vergen.workspace = true
vergen-git2.workspace = true
