name: Kurtosis E2E Tests
on:
  push:
    branches: [main]
  merge_group:
  pull_request:
env:
  CARGO_TERM_COLOR: always
jobs:
  simple-e2e-tests:
    runs-on: kona-runner-set
    timeout-minutes: 40
    name: simple-e2e-tests
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: taiki-e/install-action@just
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.85
      - name: Setup Go 1.24.3
        uses: actions/setup-go@v5
        with:
          # Semantic version range syntax or exact version of Go
          go-version: '1.24.3'
      - uses: jdx/mise-action@v2       # installs Mise + runs `mise install`
      - name: test with simple-kona devnet
        run: just build-devnet-and-test-e2e simple-kona node
  large-e2e-tests:
    runs-on: kona-runner-set
    timeout-minutes: 40
    name: large-e2e-tests
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: taiki-e/install-action@just
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.85
      - name: Setup Go 1.24.3
        uses: actions/setup-go@v5
        with:
          # Semantic version range syntax or exact version of Go
          go-version: '1.24.3'
      - uses: jdx/mise-action@v2       # installs Mise + runs `mise install`
      - name: test with large-kona devnet
        run: just build-devnet-and-test-e2e large-kona node
